/**
 * 
 */
export interface BusiuiiGridColConfig {
    id: number,//                   NUMBER(19)                     not null,
    func_id: number,//              number(19)                     null,
    grid_code: string,//            VARCHAR2(50)                   null,
    col_name: string,//             VARCHAR2(50)                   null,
    col_asname: string,//           VARCHAR2(50)                   null,
    col_order: number,//            int                            null,
    col_datatype: string,//         VARCHAR2(4)                    null,
    hava_url: string,//             VARCHAR2(50)                   null,
    have_primarykey: string,//      VARCHAR2(4)                    null,
    have_display: string,//         VARCHAR2(4)                    null,
    have_order: string,//           VARCHAR2(4)                    null,
    col_dict: string,//             VARCHAR2(20)                   null,
    col_style: string,//            VARCHAR2(500)                  null,
    col_width: string,//            VARCHAR2(100)                  null,
    col_postil: string,//           VARCHAR2(100)                  null,
    input_type: string,//           VARCHAR2(4)                    null,
    have_required: string,//        VARCHAR2(4)                    null,
    validate_rules: string,//       VARCHAR2(4)                    null,
    other_validate_rules: string,// VARCHAR2(100)                  null,
    if_editable: string,//          VARCHAR2(100)                  null,
    value_logic: string,//          VARCHAR2(200)                  null,
    ASSIGN_LOGIC: string,//         VARCHAR2(200)                  null,
    col_min: number,//              number(19)                     null,
    col_max: number,//              number(19)                     null,
    col_precision: number,//        number(19)                     null,
    COL_MAXLENGTH: number,//        number(19)                     null,
    IF_DISPLAY: string,//           VARCHAR2(100)                  null,
    STATISTICS_TYPE: string,//      VARCHAR2(4)                    null,
    STATISTICS_LABLE: string,//     VARCHAR2(100)                  null,
    STATISTICS_NAME: string,//      VARCHAR2(100)                  null,
    HAVE_CHECKED_TOP: string,//     VARCHAR2(4)                    null,
}