export interface BusiuiGridConfigModel{
   id:number,//                  NUMBER(19)                     not null,
   func_id:number,//              number(19)                     null,
   grid_code:string,//            VARCHAR2(50)                   null,
   grid_type:string,//            VARCHAR2(4)                    null,
   desc_grid_code:string,//       VARCHAR2(50)                   null,
   DESC_GRID_func_ID:string,//    VARCHAR2(50)                   null,
   have_checked:string,//         VARCHAR2(4)                    null,
   have_page:string,//            VARCHAR2(4)                    null,
   page_size:number,//            int                            null,
   init_sql:string,//             VARCHAR2(4000)                 null,
   micro_service:string,//        VARCHAR2(4)                    null,
   API:string,//                  VARCHAR2(500)                  null,
   row_style_rule:string,//       VARCHAR2(500)                  null,
   col_op_display:string,//       VARCHAR2(4)                    null,
   have_scoller:string,//         VARCHAR2(4)                    null,
   HEADER_PLACE:string,//         VARCHAR2(4)                    null,
   HAVE_BORDER:string,//          VARCHAR2(4)                    null,
   HEAD_MSG:string,//             VARCHAR2(500)                  null,
   BOTTOM_MSG:string,//           VARCHAR2(500)                  null,
}