export const VIEW = [

    '<div class="panel-body" style="padding-bottom:0px;">',
    '<div style="margin-bottom:10px">',
    '<ul class="nav nav-tabs">',
    '<li role="presentation" class="active"><a href="#">Home</a></li>',
    '<li role="presentation"><a href="#">Profile</a></li>',
    '<li role="presentation"><a href="#">Messages</a></li>',
    
    '</ul>',
    '</div>',
    '    <div class="panel panel-default">',
    '      <div class="panel-heading">查询条件</div>',
    '      <div class="panel-body">',
    '        <form id="formSearch" class="form-horizontal">',
    '          <div style="margin-top:15px">',
                    
    // ' <div class="col-md-4"><busiui-checkbox class="form-group" conf=\'{\"lable\":\"部门\",\"ngModel\":\"Name\"}\'></busiui-checkbox></div>',
    // '            <div class="col-md-4"><busiui-radio class="form-group" conf=\'{\"lable\":\"上级\",\"ngModel\":\"department\"}\'></busiui-radio></div>',
    // '            <div class="col-md-4"><busiui-select class="form-group" conf=\'{\"lable\":\"级别\",\"ngModel\":\"level\"}\'></busiui-select></div>',
    // '            <div class="col-md-4"><busiui-input class="form-group" conf=\'{\"ngModel\":\"desc\"}\'></busiui-input></div>',     
    // '            <label class="control-label col-sm-1" for="txt_search_statu">状态</label>',
    // '            <div class="col-sm-3">',
    // '              <input type="text" class="form-control" id="txt_search_statu">',
    // '            </div>',
    '<div class="col-md-4"></div><div class="col-md-4"></div>',
    '            <div class="col-md-4" style="text-align:left;">',
    '              <button type="button" style="margin-left:50px" id="btn_query" class="btn btn-primary">查询</button>',
    '            </div>',
    '          </div>',
    '        </form>',
    '      </div>',
    '    </div>',
    '',
    '    <div id="toolbar" class="btn-group">',
    '      <button id="btn_add" type="button" class="btn btn-default">',
    '        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新增',
    '      </button>',
    '      <button id="btn_edit" type="button" class="btn btn-default">',
    '        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>修改',
    '      </button>',
    '      <button id="btn_delete" type="button" class="btn btn-default">',
    '        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>删除',
    '      </button>',
    '    </div>',
    '    <table id="tb_departments"></table>',
    '  </div>'
];