export const VIEW = [
    '<div class="panel panel-default">',
    '      <div class="panel-heading">查询条件</div>',
    '      <div class="panel-body">',
    '        <form id="formSearch" class="form-horizontal">',
    '          <div style="margin-top:15px">',
    '${select}',              
    '<div class="col-md-4"></div><div class="col-md-4"></div>',
    '            <div class="col-md-4" style="text-align:left;">',
    '              <button type="button" style="margin-left:50px" id="btn_query" class="btn btn-primary">查询</button>',
    '            </div>',
    '          </div>',
    '        </form>',
    '      </div>',
    '    </div>',
];