export const VIEW = [
    '<div class="panel panel-default">',
    '      <div class="panel-heading">查询条件</div>',
    '      <div class="panel-body">',
    '        <form id="formSearch" class="form-horizontal">',
    '          <div style="margin-top:15px">',
    '${select}',              
    // ' <div class="col-md-4"><busiui-checkbox class="form-group" conf=\'{\"lable\":\"部门\",\"ngModel\":\"Name\"}\'></busiui-checkbox></div>',
    // '            <div class="col-md-4"><busiui-radio class="form-group" conf=\'{\"lable\":\"上级\",\"ngModel\":\"department\"}\'></busiui-radio></div>',
    // '            <div class="col-md-4"><busiui-select class="form-group" conf=\'{\"lable\":\"级别\",\"ngModel\":\"level\"}\'></busiui-select></div>',
    // '            <div class="col-md-4"><busiui-input class="form-group" conf=\'{\"ngModel\":\"desc\"}\'></busiui-input></div>',     
    // '            <label class="control-label col-sm-1" for="txt_search_statu">状态</label>',
    // '            <div class="col-sm-3">',
    // '              <input type="text" class="form-control" id="txt_search_statu">',
    // '            </div>',
    '<div class="col-md-4"></div><div class="col-md-4"></div>',
    '            <div class="col-md-4" style="text-align:left;">',
    '              <button type="button" style="margin-left:50px" id="btn_query" class="btn btn-primary">查询</button>',
    '            </div>',
    '          </div>',
    '        </form>',
    '      </div>',
    '    </div>',
];